- name: Nginx install and run
  hosts: wed
  become: Yes
  tasks:
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      sate: present
  - name: run Nginx
    ansible.builtin.service:
      name: nginx
      sate: started
      enable: yes











# - name: install and run my sql
#   Host: web
#   Tasks:
#   - Name: install mysql
#     ansibe.builtin:package:
#     Name: mysql
#     sate: install
#   - Name: run mysql
#     ansible.builtin.service:
#     sate: started
#     enable: No
