- Name: varibles to print
  Hosts: web
  vars: #paly level all Tasks in this play have access to this
    course: "devops with AWS"
    Duration: "140HRS"
    Trainer: "Naveen"
  Tasks:
  - Name: print the infromation
    ansible.builtin.debug:
      msg: "Hi, i am learning: {{course}},Duration: {{Duration}}, Trainer: {{Trainer}}"
  - Name: print infromation again
    vars: #task level varibles 
      course: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, i am learning: {{course}},Duration: {{Duration}}, Trainer: {{Trainer}}"
  - Name: print the infromation
    ansible.builtin.debug:
      msg: "Hi, i am learning: {{course}},Duration: {{Duration}}, Trainer: {{Trainer}}"
    
