#general removeing 

- Name: uninstalling packages
  Hosts: web
  become: yes
  Tasks:
    - Name: uninstalling negnix
      ansible.duiltin.pacakage:
        Name: negnix
        state: absent
    - Name: removing mqsyl
      ansibel.builtin.pacakage:
        Name: mysql
        state: absent

# removing packs using loops

- Name: removing packs
  Hosts: web
  Become: yes
  vars:
    packages_to_install:
      - git
      - mysql
    pacakages_to_uninstall:
      - Nginx
      - postfix
  Tasks:
  - Name: installing
    ansible.builtin.pacakage:
      Name: "{{ item }}"
      satae: present
    loop: "{{packages_to_install }}"
    when: ansible_os_family == "redhat"
  - Name: uninstalling
    ansible.builtin.pacakage:
      Name: "{{ item }}"
      state: absent
    loop: "{{ pacakages_to_uninstall }}"
    when: ansible_os_family == "Debian"

