- Name: convert map to list
  Hsost: local
  connection: local
  vars:
    course:
      Name: "devops with aws"
      duration: "120"
      trainer: "Naveen"
  Tasks:
  - Name: convert map to list
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"
      
