- Name: convert list to map
  Hsost: local
  connection: local
  vars:
    course:
      - { "key": "name", "value": "Devops with aws"}
      - { "key": "duration", "value": "120"}
      - { "key": "trainer", "value": "Naveen"}
  Tasks:
  - Name: convert list to map
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"
    
