- name: install pack if it is dnf
  hosts: web
  tasks:
  - name: install pack if dnf
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    when: ansible_os_family == "redhat"

  - name: install pack if dnf
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    when: ansible_os_family == "Debian"