# - name: install pack if it is dnf
#   hosts: web
#   tasks:
#   - name: install pack if dnf
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: present
#     loop:
#     - nginx
#     - httpd
#     when: ansible_os_family == "redhat"

#   - name: install pack if apt
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: present
#     loop:
#     - nginx
#     - httpd
#     when: ansible_os_family == "Debian"


- name: install pack if it is dnf
  hosts: web
  tasks:
  - name: print the statistics
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: install pack if dnf
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    when: ansible_os_family == "RedHat"

  - name: install pack if apt
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    when: ansible_os_family == "Debian"